# Generated by Django 2.2.28 on 2022-11-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addresspgizxdutzf'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresspgizxdutzf',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
